---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Writing your lab"
      solveButton: true
    - name: module-02
      label: "Antora"
      solveButton: true
    - name: module-03
      label: "Tabs"

tabs:
  - name: ">_ host1"
    url: /wetty
  - name: ">_ host2"
    url: /wetty2
  - name: "Developer logs"
    url: /logs/
  - name: "Asciidoc Doc"
    url: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
    external: true
