{{- if .Values.operator.install }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ include "aap-operator.fullname" . }}
  namespace: {{ include "aap-operator.namespace" . }}
  labels:
    {{- include "aap-operator.labels" . | nindent 4 }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetNamespaces:
    - {{ include "aap-operator.namespace" . }}
{{- end }}
