{{- if and .Values.admin.password (not .Values.admin.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.instanceName }}-admin-password
  namespace: {{ include "aap-operator.namespace" . }}
  labels:
    {{- include "aap-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-password
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  password: {{ .Values.admin.password | quote }}
{{- end }}
