---
# Foreman deployment via Helm chart
virtualmachines: []
containers:
  - name: foreman-tooling
    image: quay.io/foreman/foreman-toolbox:latest
    terminals:
      - name: foreman-cli
        command: /bin/bash
